[start]
cmd = "./start-production.sh"

[variables]
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["npm run build"]