# FORCE DISABLE CADDY COMPLETELY
[providers]
node = true

# EXPLICITLY DISABLE ALL OTHER PROVIDERS
[variables]
NODE_ENV = "production"
PORT = "3000"
NO_CADDY = "true"

# OVERRIDE ALL PHASES TO PREVENT CADDY
[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.caddy]
# DISABLE CADDY PHASE COMPLETELY

[phases.install]
cmds = ["npm ci"]

[phases.build] 
cmds = ["npm run build"]

[start]
cmd = "npm start"